### PR TITLE
updated to fix corner case

### PR DESCRIPTION
**Pull request by awaisabbas006**

### CODE REVIEW

**Comment by awaisabbas006** [comment]
[Thierry]: why do you put "break;" at lines 2190 and 2199. Also I would need to look at some point at "find_io_clk". Does it process cell when it is sequential also ?

Hi @BessonThierry I put break because a certain IO can drive or be driven by more than one cell, If we find an associated clock with the cell then we break, because at this point of time our reporting infrastructure does not allow us to report more than one associated clock for a single IO, so by the time I got clock I break it, This is helpfull specially in case of clock and reset which is fanin of many cells.

To your second question yes, I added sequential cells also later in the flow in clockdomainmerge table, So that we can find an associated clock if IOs are driven by or drive a sequential cell.

**Comment by BessonThierry** [comment]
Ok please can you : 

1. yes you need to break when you find a clock in the cell you are visiting. You were breaking systematically after cell visit (having or not a clk domain).
2. You need to put comments explaining what you just explained: "we break right now after finding a first clock because right now we are processing only one clock later .... but we have to revisit this part of code when we will accept several clocks ..."
3. Honnestly it would be better to process the general case right now, even if at the end you pick up only one clock. The problem of doing partial/unfinished work in several places is that it starts to be messy and it is always more difficult to get back to finish the job because we have to re-understand the code.
4. try to put systematically { brackets even if there is only one line after the "if". This is to avoid confusion sometime so that th eIF block is already there (in case you want to add extra lines).

**Comment by awaisabbas006** [comment]
Hi Thierry,

I already changed it, if we find a clock than break the loop, please look into files changed in this PR

**Comment by BessonThierry** [comment]
yes my point 1 was about my first comment : "why did you break systematically". You break now on first clock extraction success but again (point 3) you would need to extract all the clocks ... then later pick up the first one if you want. Also please put comments (point 2). Thanks

**Comment by awaisabbas006** [comment]
Hi @thierryBesson  please review latest commit

**Review by BessonThierry — APPROVED** [review]

**Pull request merged**
